name: Setup
description: Setup Env

runs:
  using: composite
  steps:
    - name: Upload Artifact universal
      if: env.PACKAGE_TYPE != 'Android_SL'
      uses: actions/upload-artifact@v4
      with:
        name: app-v${{ env.PACKAGE_VERSION }}-universal-release
        path: android/app/build/outputs/apk/release/${{ env.PACKAGE_NAME }}-v${{ env.PACKAGE_VERSION }}-universal.apk
        if-no-files-found: warn
        retention-days: 1
        compression-level: 9
